### ISSUE TITLE
FFA-90 Refactor the filter using chips in favor of a custom dialog

### ISSUE THREAD

**Issue by Coshiloco** [apptolast/FamilyFilmApp#111]
Chips visually refactor to make them look nicer as you suggested, I'll send you screenshots of what we wanted.
The aim is to be able to perform a multi-selection of genres in order to filter the list. 

RefactorTags
<img src="https://github.com/apptolast/FamilyFilmApp/assets/79223844/8bc40f04-a306-425d-a544-8380473233de" width="300" >

Old 
<img src="https://github.com/apptolast/FamilyFilmApp/assets/79223844/fe2b2bc1-f2ed-47f5-9594-c31da25ea4bb" width="300" >

**Comment by hgarciaalberto** [comment]
@javymarmol que tal van los avances?

**Comment by hgarciaalberto** [comment]
Not needed anymore
